[package]
name = "amoeba-cli"
version = "0.1.0"
authors = ["esynr3z <esynr3z@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.0"
arrayvec = "0.7.0"
ncurses = "5.101.0"
